check for state in show ha state response
newly booted devices after an upgrade often return null output from the show ha state command, which causes the 'state sync check' tasks to fail on a KeyError: ` 'dict object' has no attribute 'state'`. This adds a simple check to ensure the data is well-formed before performing additional logic.